baseURL = "https://beingatpm.com/"

# Enable Google Analytics by entering your tracking id
GoogleAnalytics = "UA-51731059-2"
enableRobotsTXT = true

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Technical Program Manager"
theme = "ace-documentation"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableReadmoreNav = false # set true to hide prev/next navigation, default is false
highlightClientSide = true # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

# [[menu.shortcuts]]
# name = "<i class='fab fa-github'></i>"
# url = "https://github.com/vantagedesign/ace-documentation"
# weight = 10

# Logo
# logo = /logo.svg
